### ISSUE TITLE
Rayyan Screenshots

### ISSUE THREAD

**Issue by AbigaleJiang** [itchyshin/bibliometrics_2022#10]
Hi Shinichi and Losia,

I have finished the labelling on the Rayyan website. I labelled the publications twice. One is for species and the other is for the detailed impacts of climate change. After our meeting, I think focusing on 'the relationships between the impacts of climate change and marine mammals' is better for my project. When I labelled publications, I re-screened and excluded the publications about methodology introduction and conservation policy. Therefore, I have around 250 publications that can be used for data analysis.

Thank you

<img width="1389" alt="截屏2022-07-08 04 04 58" src="https://user-images.githubusercontent.com/106580777/177865289-528dcd4b-7642-480d-9d3e-fd837016760a.png">
<img width="1389" alt="截屏2022-07-08 04 05 56" src="https://user-images.githubusercontent.com/106580777/177865349-7b0610cb-18d8-4420-b14a-f30cd5eb27b1.png">

**Comment by itchyshin** [comment]
Geat @AbigaleJiang - now try to read it into R - keep it going
