### ISSUE TITLE
Providing a piece of code for Cord Diagram

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/bibliometrics_2022#15]
@itchyshin 

- [ ] provide @madshowie and @AbigaleJiang with the code for Cord Diagram - using the Scopus data frame

**Comment by itchyshin** [comment]
@AbigaleJiang and @madshowie  - this Rmd has relevant code (country collaboration and term-based cord diagram - try yourself and ask for help!)

https://github.com/elmacartney/Nongen_map_of_reviews/blob/main/R/Old/Objective_Three.Rmd

**Comment by madshowie** [comment]
Hi Shinichi, I've been tug-o-warring with this code. For some reason my R isn't registering the 'circos.clear()' function. I'm not sure if this is super important but I have the circlize package loaded and it still says "Error in circos.clear() : could not find function "circos.clear"" when I try to run it.

**Comment by itchyshin** [comment]
@madshowie - I think I had a similar problem - can you actually try

library(circulize) just before running the code and try again?

@mlagisz - remember I had a similar problem and how we fixed it? - is it some version issue as well?

**Comment by madshowie** [comment]
Hmmm that didn't seem to work either. I'll keep searching online and see if I can come up with something.

**Comment by madshowie** [comment]
I think I fixed it. It seems that we need to have igraph loaded as well so I'll see how that goes!

**Comment by mlagisz** [comment]
@Maddi
Here is fixed code for your chord diagram:

```{Country collaborations v2}
bib3 <- metaTagExtraction(bib, Field = "AU_CO", sep = ";") 
NetMatrix <- biblioNetwork(bib3, analysis = "collaboration", network = "countries", sep = ";")

results <- biblioAnalysis(bib3, sep = ";")
S2 <- summary(object = results, k = 20 ,pause = FALSE) #pick top 20 countries
MostProdCountries <- S2$MostProdCountries #extract names of countries
MostProdCountries$Articles <- as.numeric(MostProdCountries$Articles) #change column to numeric
#countries <- MostProdCountries[ ,'Country'] #save list of names of countries in a vector
countries <- MostProdCountries[1:7,'Country'] #save list of names of countries in a vector, but only keep these with >=20 publications
countries <- trimws(countries) #remove white space after country name

net_matrix <- as.matrix(NetMatrix) #convert counts to numeric matrix
small_matrix <- net_matrix[countries, countries] #reduce matrix to the list of top countries
#diag(small_matrix) <- 0 #get rid of collaboration with same country
small_matrix[lower.tri(small_matrix)] <- 0 # getting rid of lower triangle (as this is duplication of info)

circos.clear() #prep for plotting
chordDiagramFromMatrix(small_matrix) #plotting
```

**Comment by madshowie** [comment]
Hi Losia, ahh thank you so much! This worked beautifully. I'm going to try do something similar with keywords, I'll let you know how I go!
