### ISSUE TITLE
Trouble pushing code

### ISSUE THREAD

**Issue by madshowie** [itchyshin/bibliometrics_2022#16]
Hi Shinichi,

I'm struggling to push my code with questions/issues. I have a feeling it's because I clicked on a file that I wasn't sure if I should include or not (it must have been very large!). Is there a way to delete the committed code and then re-commit? 

![Screen Shot 2022-07-15 at 6 13 08 pm](https://user-images.githubusercontent.com/106729043/179182316-89588802-3bf8-42ce-aa1a-35c1fa7bb6ae.png)

I tried to do it again with just the .rmd file but it must still be getting stuck on the first one so now it says I have 2 waiting to be pushed. 

![Screen Shot 2022-07-15 at 6 15 32 pm](https://user-images.githubusercontent.com/106729043/179182490-24c9270d-5025-47bd-8327-90bcf6601d5d.png)

**Comment by itchyshin** [comment]
@madshowie - you cannot push your AMPHBIANS.shp  it is too big - just read your warning message.

What you can do is push everything else - and send me that file via one drive link

**Comment by madshowie** [comment]
I'm not sure how I can only push the others because they've already been committed and have disappeared from the Git window. And I can't seem to get rid of the ones already committed - is there a special way to do so?

**Comment by itchyshin** [comment]
@madshowie - OK - what you can do it.

1. Save the new files somewhere 
2. Delete the current file
3. Create a folder via R studio 
4. Then, you can move new files to this new folder
5. Push new things apart from the big data file

Does it make sense?

**Comment by madshowie** [comment]
That makes sense, but unfortunately didn't work :( 

I've saved them into a new folder Maddi2 and it is just showing the files as deleted in the git tab. 

![Screen Shot 2022-07-15 at 7 05 33 pm](https://user-images.githubusercontent.com/106729043/179191832-e8956da4-3bd7-4e02-8862-6ab7635e10e4.png)

**Comment by madshowie** [comment]
Ok I fixed it! I'm just going to let it update for a little bit before I try push again. I'm going to tidy up my graphs this weekend and then hopefully finish off the bibliometric coupling graphs on Monday.

**Comment by madshowie** [comment]
The files weren't showing in my git for some reason. Here is a link to the files. Maybe on Tuesday you can take a look at my screen and see what's going on. 

https://1drv.ms/u/s!AlnYtVGXEhWBgWLmsnwK8x6jdS2Q?e=8HIX9z

**Comment by mlagisz** [comment]
Hi @madshowie <https://github.com/madshowie>,
The file is huge - it seems like you downloaded data for all Amphibians?
If this is the case, would you be able to download only data for the
species you have in your labelled references?
This should result in a much smaller and more manageable file.

**Comment by madshowie** [comment]
Hi Losia! No I don't think I can because it's straight from IUCN. However, that shapefile is for species distribution mapping which perhaps it might be easier to source externally. My main plan was to compare country productivity with species distribution so if I can't do the map myself I can always download the map from IUCN and compare with country productivity. Do you think this would be ok?

**Comment by mlagisz** [comment]
hi, yes, the  easier way is better - if you can download individual maps
and compare manually, this will be good.
