### ISSUE TITLE
Question of the world map of first author's country

### ISSUE THREAD

**Issue by AbigaleJiang** [itchyshin/bibliometrics_2022#17]
Hi Shinichi and Losia,
I have a problem when I check my figures. The following figures are a world map of the countries of the first author and a fig of the most productive countries.
 
![Country of first author](https://user-images.githubusercontent.com/106580777/179689362-29efc8dd-af88-44d1-83dd-8bb58275ffcb.JPG)

<img width="967" alt="Most Prodctive Countries" src="https://user-images.githubusercontent.com/106580777/179689245-f51b715a-44c4-4e15-9e94-75637de2e6b0.png">

I found in the 'fig of most productive countries, that Australia is the fourth country. But on the world map, Australia is not dyed. I used the code from the example provided by Shinichi in issue #15. I also screenshot my code in the following. 

<img width="796" alt="code" src="https://user-images.githubusercontent.com/106580777/179689460-b84b87db-24db-41bf-971f-52d183e6c003.png">

I cannot find a method to solve this problem. Which step should I fix?

**Comment by mlagisz** [comment]
Abigale, 
Your AU_CO column in firstcountrycounts contains countries of all authors separated by ;
Becouse of this most records do not get matched correctly with the map data frame (only a few records with a single author get matched correctly!).
You need to create a new column in firstcountrycounts with only the first word of each AU_CO (see some suggestions on how to do this: https://stackoverflow.com/questions/31925811/extract-first-word-from-a-column-and-insert-into-new-column).
Once you have a single country (of the first author) for each record, and all are formatted correctly, it will merge and plot correctly.

**Comment by AbigaleJiang** [comment]
Thanks Losia. I will try it!
