### ISSUE TITLE
Maddi's Plan - Week 8/9

### ISSUE THREAD

**Issue by madshowie** [itchyshin/bibliometrics_2022#18]
Hi Shinichi and Losia,

The plots I have created so far are attached below. I'm still working on some graphs to help visualise my points however they are proving to be difficult! If I can't get them by the end of the week I will have to part ways with them and use the plots that I have. I'm working on the publication trend graph as well, trying to split the orders (If I can't, I will just present it as one line). 

**Objectives**

- [ ] Choose final plots and format correctly
- [x] Submit outline for final report (Friday)
- [ ] Tidy up r code for r markdown file (by Friday WK9)
- [ ] Clean introduction (by EOD Sunday)
- [ ] Finish writing methods (by EOD Sunday)
- [ ] Finish writing results and discussion (by EOD Wednesday)
- [ ] Abstract, conclusion, and figures (by Friday WK9)
- [ ] Form presentation 
- [ ] Form twitter conference

**Plots (so far)**

Country Collaboration on Amphibian Publications:
![*Country Collaboration on Amphibian Publications](https://user-images.githubusercontent.com/106729043/180159462-3481af89-6924-4f9e-a6b7-398438241b75.jpeg)

Described vs. Studied Amphibian Species - _not sure whether to include these plots together or separately due to the large difference in sample size. If including separately, I am working on a pie graph instead for the studied species to better show proportions in publications (let me know your thoughts):_
![*Described vs  Studied Amphibian Species](https://user-images.githubusercontent.com/106729043/180159475-12a45728-d7fa-4fcd-a60b-bd114602b803.jpeg)

Keyword Co-Occurrence Chord Diagram - _not sure if this will be useful, would like to do this for orders but am struggling:_
![*Keyword Co-Occurrence Chord Diagram](https://user-images.githubusercontent.com/106729043/180159485-05b6736a-86ca-4907-8671-e5e4a5fce115.jpeg)

Publication Frequency vs. Population Trend:
![*Publication Frequency vs  Population Trend](https://user-images.githubusercontent.com/106729043/180159489-a5c9c034-d203-43c6-bf64-30c633bc65be.jpeg)

Publication Frequency vs. Threatened Status:
![*Publication Frequency vs  Threatened Status](https://user-images.githubusercontent.com/106729043/180159492-4fe3ca47-7634-479f-9a99-006661c661e0.jpeg)

Word Cloud of Common Keywords:
![Word Cloud](https://user-images.githubusercontent.com/106729043/180164053-257042d2-a451-4390-b3ef-edf8f2028473.jpeg)

**Plots that are maybes - could be useful but I want to start writing first**

Cause of Habitat Loss in Publications:
![?Cause of Habitat Loss in Publications (Labels)](https://user-images.githubusercontent.com/106729043/180162099-24987785-4bf6-4a8f-9422-0e41d52e1ae1.jpeg)

Percentage of Threatened Category within Amphibian Orders:
![?Percentage of Threatened Category Within Amphibian Orders](https://user-images.githubusercontent.com/106729043/180162308-cc3e8a1d-a974-4605-99dc-37102928d8af.jpeg)

**Other Plots** - _I've also got some plots retrieved from AmphibiaWeb with species distribution.

![Global Map - Anura Diversity ](https://user-images.githubusercontent.com/106729043/180163541-45e14214-f3d7-4f67-b8c4-08b9e0991ef9.jpeg)
![Global Map - Caudata Diversity ](https://user-images.githubusercontent.com/106729043/180163556-321c2174-2f3b-47a4-b76a-5370b57546e9.jpeg)
![Global Map - Gymnophiona Diversity ](https://user-images.githubusercontent.com/106729043/180163565-67bd73a1-4635-4645-bd84-18114c624af1.jpeg)
![Global Map of Species Richness](https://user-images.githubusercontent.com/106729043/180163570-66d3c991-e296-445a-9b8b-b1a4a2a20650.png)

**Comment by itchyshin** [comment]
@madshowie - these are looking great!! - keep going - look forward to seeing your plan
