### ISSUE TITLE
Abigale's week 9 plan

### ISSUE THREAD

**Issue by AbigaleJiang** [itchyshin/bibliometrics_2022#20]
Objectives:

- [ ] Choose final plots
- [ ] Finish introduction part
- [ ] Write methods part
- [ ] Write results part
- [ ] Modify discussion part
- [ ] Write abstract part
- [ ] Prepare presentation
- [ ] Prepare twitter conference

List of plots 

1. Annual scientific production
<img width="969" alt="Annual Scientific Production" src="https://user-images.githubusercontent.com/106580777/180381351-940f77cb-9e87-4543-af89-dc4059ea419c.png">
2. Productive countries
<img width="1056" alt="Plots of Productive Countries" src="https://user-images.githubusercontent.com/106580777/180381501-d5bb89ad-1add-4ffa-8a04-3871d6bad71e.png">
3. A world map of the first author's country
<img width="1130" alt="New world map" src="https://user-images.githubusercontent.com/106580777/180387805-feac0bc1-9477-434a-8545-e585c73aae5e.png">
4. Title co-occurrence
<img width="850" alt="Title Co-occurance" src="https://user-images.githubusercontent.com/106580777/180381760-ee83afe8-9a85-452f-99b5-e2ac133214fe.png">
5. Pie chart of species
<img width="652" alt="Proportion of focused Species " src="https://user-images.githubusercontent.com/106580777/180381887-a828825a-2d9e-43d9-87c2-b5b78bb8f640.png">
6. Pie chart of climate change impacts
<img width="544" alt="Climate Change Impacts" src="https://user-images.githubusercontent.com/106580777/180381950-f903f61b-0bcc-4170-886d-e7fd93cd2a29.png">

List of plots (might use)
1. Word cloud of keywords
<img width="533" alt="Wordcloud of keywords" src="https://user-images.githubusercontent.com/106580777/180382505-fe38a0da-ad39-4b45-b468-f3bd701c66ff.png">
2. Most productive authors
<img width="968" alt="Most Productive Authors" src="https://user-images.githubusercontent.com/106580777/180382624-35fa2622-4b7a-4893-abc6-27dc6ab511f3.png">

**Comment by itchyshin** [comment]
@AbigaleJiang - looks great too - keep it coming!
