### ISSUE TITLE
Question - conservation papers

### ISSUE THREAD

**Issue by madshowie** [itchyshin/bibliometrics_2022#5]
Hi Shinich and Losia, 

I have a question about including some papers. Do you think I should be including papers on conservation efforts/strategies for amphibians? I'm not too sure because it's not exactly documenting biodiversity, but it is responding to it. 

Also, do you think it would be ok to include papers on habitat requirements (as long as it refers to biodiversity loss/not receiving optimal requirements)?

Thanks!

**Comment by mlagisz** [comment]
probably exclude these - but first refer to your aims - you may want to re-clarify these

**Comment by itchyshin** [comment]
I agree with @mlagisz - look at your aims and as you screen papers. If there are a lot of these and if you do not include these you lose a lot then you may need to reconsider. Also, you need to build up your inclusion criteria profile @madshowie

**Comment by madshowie** [comment]
Ok, thank you! My inclusion criteria other than the order names is basically any anthropogenic land uses (i.e. mining, logging, roads etc.) resulting in habitat loss. So perhaps I will exclude conservation papers. 

I have just about finished my screening (I just need to go through the 'maybes'), and I only have 186 papers. Do you think this will be ok?

**Comment by madshowie** [comment]
What's also very interesting is there were 5 papers on Caecilians but were not an appropriate study design, so I actually have 0 papers on Caecilians!

**Comment by itchyshin** [comment]
@madshowie - I think 186 is a good number - it would be fairly easy to code things up if you want to.
