### ISSUE TITLE
Question - publications without species

### ISSUE THREAD

**Issue by madshowie** [itchyshin/bibliometrics_2022#7]
Hi Shinichi and Losia, 

I am wondering if we should label the publications that don't have species name in the abstract? Maybe "multiple species"?

Thanks!

**Comment by itchyshin** [comment]
Yes @madshowie but hopefully you can label it at the order level

**Comment by madshowie** [comment]
I've gone through and labelled them all into orders, now I've reloaded the included publications and am labelling them with their species names. For those that don't include the species name, is it best to assign the label 'multiple species' or am I able to leave it with the order label?

**Comment by itchyshin** [comment]
You can still label "multiple species" which may make R coding easier later on

**Comment by madshowie** [comment]
Ok great thank you!
