### ISSUE TITLE
Rayyan labelling screenshots

### ISSUE THREAD

**Issue by madshowie** [itchyshin/bibliometrics_2022#8]
Hi Shinichi and Losia, 

I've completed all the labelling in Rayyan (hopefully!). Just sending through some screenshots of what I did. I first labelled them by 'Amphibia' or their individual Order, as well as cause of habitat loss. Then I exported, and re-imported the included publications and labelled them with species name or 'Multiple species'.

![First screening](https://user-images.githubusercontent.com/106729043/177505662-38bb7e2d-c2a6-47bc-bb64-454a02c682a7.png)
![Second screening](https://user-images.githubusercontent.com/106729043/177505671-6a271a09-1d85-4ea7-98ee-3ec60e585c42.png)

**Comment by mlagisz** [comment]
Looks good!  pls export, get the full records from Scopus and play with the code I posted on GitHub!
